Lab11

In [18]:
import numpy as np
import pandas as pd
import tensorflow as tf
import pathlib
import random
import keras
import keras.models as M
import keras.layers as L
import keras.backend as K

from google.colab import files, drive
from sklearn.model_selection import train_test_split


In [19]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [20]:
csvs =  sorted(str(p) for p in pathlib.Path('/content/drive/MyDrive/FontsPZNM/fonts').glob("*.csv"))

data = pd.DataFrame()
for csv in csvs[::2]:
  data = data.append(pd.read_csv(csv))

display(data.iloc[random.sample(range(0, len(data.index)), 10)])

<ipython-input-20-3f3ac343d04f>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(pd.read_csv(csv))
<ipython-input-20-3f3ac343d04f>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(pd.read_csv(csv))
<ipython-input-20-3f3ac343d04f>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(pd.read_csv(csv))
<ipython-input-20-3f3ac343d04f>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(pd.read_csv(csv))
<ipython-input-20-3f3ac343d04f>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  da

font       fontVariant  m_label  strength  italic  orientation  \
27312   HANDPRINT           scanned       56       0.4       0          0.0   
60004   HANDPRINT           scanned       55       0.4       0          0.0   
59588   HANDPRINT           scanned       52       0.4       0          0.0   
543           TAI  MICROSOFT TAI LE      115       0.4       1          0.0   
14992  CREDITCARD           scanned       54       0.4       0          0.0   
52776        OCRB           scanned       48       0.4       0          0.0   
31965   HANDPRINT           scanned       51       0.4       0          0.0   
992       SIMPLEX           SIMPLEX      170       0.7       0          0.0   
73756        OCRB           scanned       48       0.4       0          0.0   
57672   HANDPRINT           scanned       52       0.4       0          0.0   

       m_top  m_left  originalH  originalW  ...  r19c10  r19c11  r19c12  \
27312      0       0         20         13  ...     177     129      40   
60004      0       0         20         10  ...       1       1       1   
59588      0       0         20         12  ...       1      25      74   
543       47      24         36         31  ...      37       1       1   
14992      0       0         54         35  ...     133     136     127   
52776      0       0         14          8  ...     255     255     255   
31965      0       0         20         20  ...      60     140     141   
992       38      26         18         15  ...     255     255     255   
73756      0       0         27         25  ...     142      67      67   
57672      0       0         20         18  ...       1       1       1   

       r19c13  r19c14  r19c15  r19c16  r19c17  r19c18  r19c19  
27312       1       1       1       1       1       1       1  
60004       1       1       1       1       1       1       1  
59588     158     201     179     139      61      21       1  
543         1       1       1       1       1       1       1  
14992     127     127     118     101     107     106     103  
52776     255     255     255     255     128       1       1  
31965     216     253     152      79      10       1       1  
992       255     255     255     255     255     171       1  
73756     116      76       1       1       1       1       1  
57672       1       1       1       1       1       1       1  

[10 rows x 412 columns]

In [21]:
factorized = pd.factorize(data['font'])
data['font'] = factorized[0]
unique_cats_count = len(factorized[1])

print(f"Unique categories: {unique_cats_count}")

display(data.iloc[random.sample(range(0, len(data.index)), 10)])

Unique categories: 77


font           fontVariant  m_label  strength  italic  orientation  \
1294     31  GILL SANS ULTRA BOLD      228       0.4       0          0.0   
753       9         BUXTON SKETCH     1028       0.4       1          0.0   
658      14               CHILLER       88       0.7       0          0.0   
20228    51               scanned       70       0.4       0          0.0   
11451    51               scanned       60       0.4       0          0.0   
42505    51               scanned       76       0.4       0          0.0   
295      37     IMPRINT MT SHADOW      249       0.4       1          0.0   
2062     50               scanned       57       0.4       0          0.0   
134      28      FRENCH SCRIPT MT      178       0.4       0          0.0   
64559    34               scanned       55       0.4       0          0.0   

       m_top  m_left  originalH  originalW  ...  r19c10  r19c11  r19c12  \
1294      36      23         51         40  ...     255     255     255   
753       36      27         42         36  ...      80       9       1   
658       35      19         42         33  ...     134      69       1   
20228      0       0         28         21  ...       1       1       1   
11451      0       0         15         14  ...      19      30      48   
42505      0       0         25         19  ...     154     164     150   
295       38      27         45         35  ...     166     175     142   
2062       0       0         15          8  ...       1       1       1   
134       45      22         17         13  ...     255     255     255   
64559      0       0         20         10  ...       1       1       1   

       r19c13  r19c14  r19c15  r19c16  r19c17  r19c18  r19c19  
1294      255     255     255     255     255     255     255  
753         1       1       1       1       1       1       1  
658         1       1       1       1       6      13      13  
20228       1       1       1       1       1       1       1  
11451     110     172     200     209     160     101      33  
42505     126     110     124     131      76      26       6  
295       142     126      29      29       5       1       1  
2062        1       1       1       1       1       1       1  
134       255     255      99       1       1       1       1  
64559       1       1       1       1       1       1       1  

[10 rows x 412 columns]

In [22]:
train, test = train_test_split(data, test_size=0.15)

In [23]:
ignored_columns_for_train = ["font", "fontVariant", "m_label", "strength", "italic", "orientation", "m_top", "m_left", "originalH", "originalW", "h", "w"]

train_y = np.array(train["font"])
train_x = train.drop(columns=ignored_columns_for_train)

test_y = np.array(test["font"])
test_x = test.drop(columns=ignored_columns_for_train)
train_y_oh = keras.utils.to_categorical(train_y, unique_cats_count)
test_y_oh = keras.utils.to_categorical(test_y, unique_cats_count)
train_x = train_x.to_numpy()
test_x = test_x.to_numpy()
print(train_x)

[[  1   1   2 ... 150 125  73]
 [  1   1 128 ...   1   1   1]
 [255 255 255 ...   0   0   0]
 ...
 [136 137 137 ... 152 144 144]
 [  1   1   1 ...   1   1   1]
 [114 251 125 ... 125 251 114]]


In [24]:
train_x = train_x.reshape((len(train_x), 20, 20, 1))
train_x = train_x.astype('float32') / 255

test_x = test_x.reshape((len(test_x), 20, 20, 1))
test_x = test_x.astype('float32') / 255

K.clear_session()

model = M.Sequential()
model.add(L.Conv2D(20, (3,3), activation='relu', input_shape= (20, 20, 1)))
model.add(L.Conv2D(20, (2,2), activation='relu'))
model.add(L.BatchNormalization())
model.add(L.Conv2D(40, (2, 2), activation='relu'))
model.add(L.Flatten())
model.add(L.Dense(unique_cats_count, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
results = model.fit(train_x, train_y_oh, batch_size=64, epochs=15, validation_data=(test_x, test_y_oh))

Epoch 1/15
5335/5335 [==============================] - 333s 62ms/step - loss: 1.4962 - accuracy: 0.6312 - val_loss: 1.2626 - val_accuracy: 0.6796
Epoch 2/15
5335/5335 [==============================] - 337s 63ms/step - loss: 1.0052 - accuracy: 0.7335 - val_loss: 1.1468 - val_accuracy: 0.7084
Epoch 3/15
5335/5335 [==============================] - 345s 65ms/step - loss: 0.8015 - accuracy: 0.7785 - val_loss: 1.1793 - val_accuracy: 0.7148
Epoch 4/15
5335/5335 [==============================] - 335s 63ms/step - loss: 0.6815 - accuracy: 0.8079 - val_loss: 1.1347 - val_accuracy: 0.7294
Epoch 5/15
5335/5335 [==============================] - 333s 63ms/step - loss: 0.6039 - accuracy: 0.8264 - val_loss: 1.1722 - val_accuracy: 0.7273
Epoch 6/15
5335/5335 [==============================] - 337s 63ms/step - loss: 0.5489 - accuracy: 0.8407 - val_loss: 1.1940 - val_accuracy: 0.7347
Epoch 7/15
5335/5335 [==============================] - 362s 68ms/step - loss: 0.5066 - accuracy: 0.8519 - val_loss: 1

In [25]:

print(f"Accuracy: {np.max(results.history['accuracy'])}")

Accuracy: 0.894612729549408


In [26]:
!pip install -q typing-extensions==4.5.0 kaleido accelerate transformers ftfy bitsandbytes==0.35.0 gradio natsort safetensors xformers
import gradio as gr

fonts = data["fontVariant"]

def identify_font(img):
  img = img.reshape(1, 20, 20, 1)
  prediction = model.predict(img).tolist()[0]
  return {fonts[i]: prediction[i] for i in range(len(fonts))}

iface = gr.Interface(
    fn = identify_font,
    inputs = gr.Image(type="pil"),
    outputs = gr.Label(),
)
iface.launch(share=True)

IMPORTANT: You are using gradio version 3.0, however version 3.14.0 is available, please upgrade.
--------
Colab notebook detected. To show errors in colab notebook, set debug=True in launch()


ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



*** Failed to connect to ec2.gradio.app:22: [Errno 110] Connection timed out
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/tunneling.py", line 81, in create_tunnel
    client.connect(
  File "/usr/local/lib/python3.10/dist-packages/paramiko/client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-26-f4b69bb97062>", line 16, in <cell line: 16>
    iface.launch(share=True)
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 517, in launch
    share_url = networking.setup_tunnel(self.server_port, None)
  File "/usr/local/lib/python3.10/dist-packages/gradio/networking.py", line 175, in setup_tunnel


TypeError: ignored